{
 "title": "SystaComfort",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Störung",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "clamp_max((65535-systacomfort_boiler_error_info), 1)"
    }
   ]
  },
  {
   "title": "Temperaturen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "systacomfort_outside_temperature_celsius",
     "legendFormat": "Fühler Eingang"
    },
    {
     "expr": "systacomfort_solarpanel_outside_temperature_celsius",
     "legendFormat": "Solarpanel"
    }
   ]
  },
  {
   "title": "Brauchwasser",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "systacomfort_boiler_loadpump_info",
     "legendFormat": "Ladepumpe"
    },
    {
     "expr": "systacomfort_tapwater_target_temperature_celsius",
     "legendFormat": "Brauchwasser Soll"
    },
    {
     "expr": "systacomfort_tapwater_temperature_celsius",
     "legendFormat": "Brauchwasser Ist"
    },
    {
     "expr": "systacomfort_watercirculation_temperature_celsius",
     "legendFormat": "Zirkulation"
    }
   ]
  },
  {
   "title": "Kessel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "systacomfort_boiler_return_temperature_celsius",
     "legendFormat": "Rücklauftemperatur"
    },
    {
     "expr": "systacomfort_boiler_supply_temperature_celsius",
     "legendFormat": "Vorlauftemperatur"
    },
    {
     "expr": "systacomfort_boiler_target_temperature_celsius",
     "legendFormat": "Kesseltemperatur Soll"
    },
    {
     "expr": "(systacomfort_boiler_return_temperature_celsius-systacomfort_boiler_supply_temperature_celsius)> bool 1.8 and systacomfort_boiler_active_info > bool 0",
     "legendFormat": "Flamme"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "systacomfort_solarpanel_return_temperature_celsius",
     "legendFormat": "Rücklauf"
    },
    {
     "expr": "systacomfort_solarpanel_supply_temperature_celsius",
     "legendFormat": "Vorlauf"
    },
    {
     "expr": "systacomfort_solarpanel_temperature_celsius",
     "legendFormat": "am Panel"
    }
   ]
  },
  {
   "title": "Heizkreis",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "systacomfort_heatercircuit_return_temperature_celsius",
     "legendFormat": "Rücklauf"
    },
    {
     "expr": "systacomfort_heatercircuit_supply_temperature_celsius",
     "legendFormat": "Vorlauf"
    },
    {
     "expr": "systacomfort_boiler_heatercircuitpump_info > bool 0",
     "legendFormat": "Heizkreispumpe"
    }
   ]
  }
 ]
}